site:
  title: TypeDB Docs Samples
  start_page: home::quickstart.adoc
content:
  sources:
  - url: https://github.com/izmalk/docs-samples.git
    start_path: tdb
    branches: HEAD
    
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true